/** Default wizard form state — shared by LoanWizard and profile sidebar builders. */
export function makeEmptyForm() {
  return {
    occupancy: "",
    primaryLoanPurpose: "",
    lienPosition: "",
    firstLienPurpose: "",
    secondLienProduct: "",
    piggybackPurpose: "",
    loanPurpose: "",
    state: "",
    valueSalesPrice: "",
    ltv: "",
    loanAmount: "",
    estimatedDti: "",
    documentationType: "",
    documentationTimeframe: "",
    prepaymentTerms: "",
    prepayStepdown: "",
    propertyType: "",
    citizenship: "",
    decisionCreditScore: "",
    firstTimeHomebuyer: "",
    investmentIncomePath: "" as "" | "income" | "dscr",
    rentalType: "",
    creditEventCategory: "",
    creditEventType: "",
    yearsSinceCreditEvent: "",
    firstTimeInvestor: "",
    establishedPrimaryRes: "",
    paymentHistory: "",
    isSecondLien: "",
    existingFirstLien: "",
    cltv: "",
    dscr: "",
    creditEvent: "",
    visaCategory: "",
    visaType: "",
    visaTypeOther: "",
    ofacSanctioned: "",
    hasUsCredit: "",
    existingSecondLien: "",
    existingSecondLienBalance: "",
    refinancingExistingSecond: "",
    existingSecondBalance: "",
    cashInHandRequest: "",
    helocDrawYears: "",
    helocInitialDraw: "",
    acreage: "",
    isRuralProperty: "",
    decliningMarket: "",
    nonOccupantCoBorrower: "",
    noCbRelationship: "",
    noCbFico: "",
    noCbIncome: "",
    combinedDti: "",
    householdSize: "",
    monthlyResidualIncome: "",
    entityVesting: "",
    tradelines: "",
    assetsLiquidFunds: "",
    giftFundsPercent: "",
    reservesMonths: "",
    loanTerm: "No preference",
    interestOnlyPref: "No preference",
    powerOfAttorney: "",
    listingSeasoning: "",
    scenarioNotes: "",
    creditEventDate: "",
    creditEventDateUncertain: "",
    selfEmploymentHistory: "",
    vacantProperty: "",
    propertyCondition: "",
    rateTypePref: "No Preference",
    stateCounty: "",
    stateCity: "",
    stateBorough: "",
    stateZipCode: "",
    isInBaltimoreCity: "",
    isInIndianapolis: "",
    isInPhiladelphia: "",
    isInMemphis: "",
    isInLubbock: "",
    hiLavaZone: "",
    recentlyRehabbed: "",
    otherFinancedProperties: "",
    reservesAvailable: "",
    nonArmsLength: "",
    departingResidence: "",
    departingRent: "",
    propertyCount: "",
    combinedPropertyValue: "",
    combinedLoanAmount: "",
    totalGrossRents: "",
    combinedPitia: "",
    loanLevelDscr: "",
    creditEvents: [] as string[],
    creditEventYears: {} as Record<string, string>,
    hasCreditEvent: "",
    creditEventDates: {} as Record<string, string>,
  };
}

export type WizardForm = ReturnType<typeof makeEmptyForm>;
